################################################################################
# ==> Tasks for install Oracle Fussion Middleware Infrastructure software
# ==> to a RHEL 7 system. Supports version 12.1.3
# ==> author: Christos Vezalis
################################################################################

# ==> Install Fussion Middleware Infrastructure
- name: Create installer directory
  file: state=directory path={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}
#- name: Copy Middleware Installer
#  copy: src={{ mw_installer }} dest={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Copy Middleware Installer
  command: "cp /tmp/{{ mw_installer }} {{ mw_installer_folder }}"
- name: Copy file for silent installation
  template: src=silent-weblogic.txt dest={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Change the permission of the tmp dir 
  command: 'chmod -R 777 /tmp'
  become_user: root

- name: Copy OraInst.loc
  template: src=oraInst.loc dest={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}
#- name: change the permission of tmp dir
#  command: "chmod -R 755 /tmp/"
- name: execute Weblogic installer
  command: "{{ jdk_folder }}/bin/java -Xms1024m -Xmx1024m -jar {{ mw_installer_folder }}/{{ mw_installer }} ORACLE_HOME=/oracle/fmw12.1.3/product/OracleHome -silent -responseFile {{ mw_installer_folder }}/silent-weblogic.txt -invPtrLoc {{ mw_installer_folder }}/oraInst.loc"
  sudo_user: '{{ oracle_user }}'
